### ISSUE TITLE
Cannot redefine exception 'name'

### ISSUE THREAD

**Issue by fabio-scala** [adriengibrat/ts-custom-error#53]
In ES6 environments, it is not possible to redefine/overwrite the name of the exception in the constructor:

```
2020-07-16T08:00:09.847Z ERROR [AppComponent]: TypeError: Cannot redefine property: name
```

Can we make this property `configurable: true` or at least writable?

Best, Fabio

**Comment by Dragoon1010** [comment]
same problem here, i have : 
`
"ERROR  Cannot assign to read only property 'name' of object 'HttpError:..."`

**Comment by adriengibrat** [comment]
It seems related to https://github.com/adriengibrat/ts-custom-error/blob/master/src/custom-error.ts#L28

Please, could you provide sample code to reproduce + info about environment (node / browser + version) ?

Do you try to overwrite exception name in you code or is it an error that happens when a custom error is constructed ?

**Comment by Dragoon1010** [comment]
@adriengibrat my code runs on a browser (but can also run on node, because it's a cross-platform SDK).

here is the sample code : 

```typescript
import { CustomError } from 'ts-custom-error';
import { HttpErrorEnum } from '../enums/HttpErrorEnum';

export class HttpError extends CustomError {
    /**
     * create new HttpError
     * @param {HttpErrorEnum} name - http Error type
     * @param {string} message - Error message
     */
    constructor (params: {
        name: HttpErrorEnum,
        message: string
    }) {
        super(params.message);

        this.name = params.name;
    }
}
```
and here is the error generated on the browser side : 
![Capture du 2020-08-10 09-25-15](https://user-images.githubusercontent.com/1273438/89760021-b362fc80-daeb-11ea-8248-0dfe49c7e892.png)

**Comment by adriengibrat** [comment]
Thanks for the request and the detailed example ;)

I made the name property configurable (see https://github.com/adriengibrat/ts-custom-error/pull/54).

IMO it's a bit safer than writable and it still allows to rename an error on purpose.

**Comment by adriengibrat** [comment]
Version [3.2.0](https://www.npmjs.com/package/ts-custom-error/v/3.2.0) should allow you to redefine custom error name like you've suggested:
```ts
import { CustomError } from 'ts-custom-error';
import { HttpErrorEnum } from '../enums/HttpErrorEnum';

export class HttpError extends CustomError {
    /**
     * create new HttpError
     * @param {HttpErrorEnum} name - http Error type
     * @param {string} message - Error message
     */
    constructor (params: {
        name: HttpErrorEnum,
        message: string
    }) {
        super(params.message);
        Object.defineProperty(this, 'name', { value: params.name });
    }
}
```

Feel free to reopen if you encouter any trouble ;)
